### ISSUE TITLE
More clarity on favoring full log to GitHub issue rather than just stacktrace

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/CrashReporter#12]
I'm wondering if the amount of users submitting a plain stacktrace alone in issues is in part due to that being the default that pops up with the CR.

Maybe we should either switch the tabs around so the full log file appears by default, and the "Stacktrace Only" tab is available if clicked? That's probably easy

Or perhaps put a better label on there encouraging users to post the full log / use the pastebin button then paste that link. But that could probably be easily ignored

**Comment by msteiger** [comment]
This should be fixed in 2.0.0.
