### ISSUE TITLE
Only include world log from most recent session?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/CrashReporter#19]
I just did a round of stable release testing meaning I played a bunch of worlds in one go, returning to the main menu and creating a new world. Then I did something I knew would crash the game and got a CR window with a pile of tabs as it offered me each world log I had played in during that game session.

That looks a bit overwhelming and confusing. We should probably only include the most recent world log? Maybe making it obvious to the user somewhere that only the most recent world log is included but they can go select more if needed

**Comment by msteiger** [comment]
I just ran into the same problem. Not sure how to tackle that, but I'll look into it.
